database:
    image: mysql:5.7
    ports:
        - "33061:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homestead
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
web:
    image: websphere-liberty:beta
    command: docker run -d -p 80:9080 --name wlp websphere-liberty
